services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stimul-ico:latest
    container_name: stimul-ico-prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Используем именованные тома для продакшна вместо локальных путей
      - db_data:/app/backend/db.sqlite3
      - static_data:/app/staticfiles
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_ALLOWED_HOSTS=your-domain.com
      - PORT=8000
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  static_data:
    driver: local
