# Generated by hand for initial schema
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('division', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('category', models.CharField(choices=[('АУП', 'Административно-управленческий персонал'), ('ППС', 'Профессорско-преподавательский состав'), ('Другое', 'Другое')], max_length=32, verbose_name='Категория')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выплата')),
                ('justification', models.TextField(blank=True, verbose_name='Обоснование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StimulusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Размер выплаты')),
                ('justification', models.TextField(verbose_name='Обоснование')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='stimuli.employee', verbose_name='Сотрудник')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Заявка на стимулирование',
                'verbose_name_plural': 'Заявки на стимулирование',
                'ordering': ['-created_at'],
                'permissions': [('view_all_requests', 'Может видеть все заявки')],
            },
        ),
    ]
