# Generated by Django 5.0.4 on 2025-09-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_time_payments", "0001_initial"),
        ("stimuli", "0005_update_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="stimulusrequest",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="В архиве с"
            ),
        ),
        migrations.AddField(
            model_name="stimulusrequest",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stimulus_requests",
                to="one_time_payments.requestcampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.AlterField(
            model_name="stimulusrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                    ("archived", "Архив"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
    ]
