# Generated by Django 5.0.4 on 2025-09-22 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionquota",
            name="occupied_fte",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=6,
                verbose_name="Занятые ставки",
            ),
        ),
        migrations.AddField(
            model_name="positionquota",
            name="vacant_fte",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=6,
                verbose_name="Вакантные ставки",
            ),
        ),
        migrations.AddField(
            model_name="positionquotaversion",
            name="occupied_fte",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=6,
                verbose_name="Занятые ставки",
            ),
        ),
        migrations.AddField(
            model_name="positionquotaversion",
            name="vacant_fte",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=6,
                verbose_name="Вакантные ставки",
            ),
        ),
    ]
