# Generated by Django 5.0.4 on 2025-11-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_time_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcampaign',
            name='auto_close_day',
            field=models.PositiveSmallIntegerField(blank=True, default=15, help_text='Устаревшее поле, будет удалено.', null=True, verbose_name='Дата автозакрытия (устарело)'),
        ),
        migrations.AlterField(
            model_name='requestcampaign',
            name='auto_close_enabled',
            field=models.BooleanField(default=True, help_text='Кампания автоматически закроется в 00:00 дня после дедлайна.', verbose_name='Автоматическое закрытие'),
        ),
    ]
