# Generated by Django 5.0.4 on 2025-09-22 08:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Месяц"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("recurring", "Постоянные выплаты"),
                            ("one_time", "Разовые выплаты"),
                        ],
                        max_length=16,
                        verbose_name="Тип бюджета",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Всего средств"
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Зарезервировано",
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Израсходовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Бюджет",
                "verbose_name_plural": "Бюджеты",
                "ordering": ["-year", "-month", "budget_type"],
                "unique_together": {("year", "month", "budget_type")},
            },
        ),
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Выделено средств"
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Зарезервировано",
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Израсходовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="budgeting.budget",
                        verbose_name="Бюджет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выделение бюджета",
                "verbose_name_plural": "Выделения бюджета",
            },
        ),
    ]
