# Generated by Django 5.0.4 on 2025-09-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgeting", "0001_initial"),
        ("one_time_payments", "0001_initial"),
        ("recurring_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetallocation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_allocations",
                to="one_time_payments.requestcampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.AddField(
            model_name="budgetallocation",
            name="recurring_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_allocations",
                to="recurring_payments.recurringperiod",
                verbose_name="Период постоянных выплат",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetallocation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("recurring_period__isnull", False), ("campaign__isnull", True)
                    ),
                    models.Q(
                        ("recurring_period__isnull", True), ("campaign__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="allocation_single_target",
            ),
        ),
    ]
