# Generated by Django 5.0.4 on 2025-09-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={
                "permissions": [("view_dashboard", "Может просматривать дэшборд")],
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
    ]
