# Generated by Django 5.0.4 on 2025-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring_payments", "0001_initial"),
        (
            "stimuli",
            "0006_stimulusrequest_archived_at_stimulusrequest_campaign_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recurringpayment",
            name="unique_employee_payment_per_period",
        ),
        migrations.RemoveField(
            model_name="recurringpayment",
            name="payment_type",
        ),
        migrations.AddField(
            model_name="recurringpayment",
            name="reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Основание выплаты"
            ),
        ),
        migrations.AlterField(
            model_name="recurringpayment",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Комментарий"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringpayment",
            constraint=models.UniqueConstraint(
                fields=("period", "employee"), name="unique_employee_payment_per_period"
            ),
        ),
    ]
