# Generated by Django 5.0.4 on 2025-09-22 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stimuli", "0005_update_rates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название кампании"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("open", "Открыта"),
                            ("closed", "Закрыта"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("opens_at", models.DateField(verbose_name="Дата открытия")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "auto_close_day",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Если дедлайн не указан, кампания автоматически закрывается в указанный день месяца.",
                        verbose_name="Дата автозакрытия",
                    ),
                ),
                (
                    "auto_close_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Автоматическое закрытие"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыта"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="В архиве с"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Кампания заявок",
                "verbose_name_plural": "Кампании заявок",
                "ordering": ["-opens_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="OneTimePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата выплаты",
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Обоснование"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="one_time_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_payments",
                        to="stimuli.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_payments",
                        to="one_time_payments.requestcampaign",
                        verbose_name="Кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разовая выплата",
                "verbose_name_plural": "Разовые выплаты",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
