# Generated by Django 5.0.4 on 2025-09-22 08:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "stimuli",
            "0006_stimulusrequest_archived_at_stimulusrequest_campaign_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("open", "Открыт"),
                            ("closed", "Закрыт"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "budget_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Лимит бюджета",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Период постоянных выплат",
                "verbose_name_plural": "Периоды постоянных выплат",
                "ordering": ["-start_date", "-end_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("allowance", "Надбавка"),
                            ("bonus", "Бонус"),
                            ("other", "Прочее"),
                        ],
                        max_length=32,
                        verbose_name="Тип выплаты",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Зафиксирована"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_payments",
                        to="stimuli.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="recurring_payments.recurringperiod",
                        verbose_name="Период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Постоянная выплата",
                "verbose_name_plural": "Постоянные выплаты",
                "ordering": ["period", "employee__full_name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringPaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "previous_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Предыдущее значение",
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Новое значение"
                    ),
                ),
                (
                    "previous_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание (до)"
                    ),
                ),
                (
                    "new_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание (после)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="Причина изменения"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_payment_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="recurring_payments.recurringpayment",
                        verbose_name="Выплата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал изменения выплаты",
                "verbose_name_plural": "Журнал изменений выплат",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="recurringpayment",
            constraint=models.UniqueConstraint(
                fields=("period", "employee", "payment_type"),
                name="unique_employee_payment_per_period",
            ),
        ),
    ]
