# Generated by Django 5.0.4 on 2025-10-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0002_positionquota_occupied_fte_positionquota_vacant_fte_and_more'),
        ('stimuli', '0006_stimulusrequest_archived_at_stimulusrequest_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='staffing.division', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_division', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подразделение пользователя',
                'verbose_name_plural': 'Подразделения пользователей',
            },
        ),
    ]
