# Generated by Django 5.0.4 on 2025-10-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stimuli', '0008_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulusrequest',
            name='final_status',
            field=models.CharField(
                blank=True,
                help_text='Статус на момент архивирования кампании',
                max_length=32,
                verbose_name='Итоговый статус'
            ),
        ),
    ]
